### ISSUE TITLE
About the performance of GraphSAGE in Table 3.

### ISSUE THREAD

**Issue by Orion-wyc** [PonderLY/PC-GNN#1]
Thank you for your exciting work!

I've got a question on the perforamance comparison in Table 3 after reading your paper:
For Amazon, the performance reported in Table 3 is (0.6416±0.0079, 0.7589±0.0046, 0.5949±0.0349) respectively.
But the result of the author implementation is inconsistent with Table 3:

```
Restore model from epoch 45
Model path: ./pytorch_models/2021-08-08 19-38-06/amazon_SAGE.pkl
   GNN F1-binary-1: 0.8481	F1-binary-0: 0.9848	F1-macro: 0.9165	G-Mean: 0.8963	AUC: 0.9324	Recall=0.8987
   GNN TP: 268	TN: 3110	FN: 62	FP: 34
F1-Macro: 0.9164508862362816
AUC: 0.9323704603284756
G-Mean: 0.8962916549983307
```
Additionally, I implement these models based on DGL, performance of GraphSAGE is:
```
[2021/08/08 19:52:01.888] Saving Model to /trained_models/fraud/amazon/SAGE_amazon.pth
[2021/08/08 19:52:01.955] AUC=0.8709 | Recall=0.8709 | Gmean=0.8646
[2021/08/08 19:52:01.955] TN= 3033 FP=   77 FN=   81 TP=  266
[2021/08/08 19:52:01.955] Best val AUC=0.8844, f1-macro=0.8844, epoch=47
[2021/08/08 19:52:01.955] Final scores: ACC=0.9543 | f1-fraud=0.7710 | f1-benign=0.9746 | f1-micro=0.9543 | f1-macro=0.8728
```

Both implementations use the same configuration, the number of neighbors sampled is set to be 5.

Is there any other setting or constrain we need to pay attention to ?

**Comment by PonderLY** [comment]
Thanks for your interest in our paper.

The performance of GraphSAGE reported in the paper is the result of regarding all relations as the same one and without any sampling techniques. Due to the class imbalance, the scores are relatively low. The results you mentioned may be GraphSAGE after the Pick process. If your implementation based on DGL has better performance, it is ok to compare with that.
