### ISSUE TITLE
About the aggregation step in this code

### ISSUE THREAD

**Issue by umnooob** [PonderLY/PC-GNN#3]
Thanks for your amazing paper!
But a problem bothered me when I read the code. 
Compared with aggregation process in paper(eq.8 eq.9), weight matrix as well as l-1 layer r relation representations of central nodes seems to be missing in this code . For example,I can't find d_l *2d_{l-1} weight matrix in IntraAgg class.Also summation operation instead of concat operation is applied to inter_agg .
Could you help me with my problems?

**Comment by PonderLY** [comment]
Hello,
Thanks for your interest in our paper. 
As you say, in the code, I remove the weight matrix of IntraAgg in order to be compatible with various aggregators in InterAgg. Consequently, the code is a little inconsistent with the equations in the paper. As you request, I will push a consistent version to the repository as soon as possible. Empirically, adding weight matrices following the paper will improve the performance a little, and PC-GNN is compatible with various aggregation strategies. I'm sorry for confusing you.
Besides, I have read your blogs about PC-GNN in this link (https://www.dengzexuan.top/2021/08/pc-gnn%E7%90%86%E8%A7%A3%E4%B8%8E%E5%AE%9E%E7%8E%B0/) and feel grateful for your attention to our work.

**Comment by umnooob** [comment]
Thank you very much and can't wait to see the new version of your code.
Thank you also for your approval, this blog was written before reading code, so there must be many mistakes, I will continue to improve and implement it. Also look forward to your advice.

**Comment by PonderLY** [comment]
The new version has been pushed. You can check it.
